spring.application.name=api_ai

spring.ai.vertex.ai.gemini.project-id=${PROJECT_ID}
# spring.ai.vertex.gemini.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash-001